const Database = require('better-sqlite3');
const db = new Database('applications.db');

// ensure columns exist
['contract_fee','grant'].forEach(col => {
  try { db.exec(`ALTER TABLE universities ADD COLUMN ${col} TEXT`); } catch {}
});

const data = [
  { id:1,  req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','IT va Dasturlash','Muhandislik','Pedagogika'], fee:'2500$/yil', grant:false },
  { id:2,  req:['Attestat'], deg:['Bachelor','Master'], dir:['Pedagogika','Iqtisodiyot va Biznes','Huquqshunoslik'], fee:'2000$/yil', grant:false },
  { id:3,  req:['Attestat'], deg:['Bachelor'], dir:['Pedagogika','Iqtisodiyot va Biznes','Muhandislik'], fee:'1800$/yil', grant:false },
  { id:4,  req:['Attestat','Biologiya imtihoni'], deg:['Bachelor','Master'], dir:['Tibbiyot','Farmatsevtika'], fee:'4000$/yil', grant:false },
  { id:5,  req:['Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Pedagogika','Huquqshunoslik','IT va Dasturlash'], fee:'1500$/yil', grant:false },
  { id:6,  req:['Attestat','Biologiya imtihoni'], deg:['Bachelor','Master'], dir:['Tibbiyot','Farmatsevtika'], fee:'3500$/yil', grant:false },
  { id:7,  req:['Attestat'], deg:['Bachelor'], dir:['IT va Dasturlash','Muhandislik','Energetika'], fee:'1500$/yil', grant:false },
  { id:8,  req:['Attestat'], deg:['Bachelor'], dir:['Pedagogika','Tilshunoslik','Psixologiya'], fee:'1200$/yil', grant:false },
  { id:9,  req:['Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Pedagogika','Huquqshunoslik'], fee:'1400$/yil', grant:false },
  { id:10, req:['Attestat'], deg:['Bachelor'], dir:['Pedagogika','Iqtisodiyot va Biznes'], fee:'1200$/yil', grant:false },
  { id:11, req:['Attestat'], deg:['Bachelor'], dir:['Pedagogika','Tilshunoslik','Psixologiya'], fee:'1200$/yil', grant:false },
  { id:12, req:['Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Huquqshunoslik','IT va Dasturlash','Pedagogika'], fee:'1500$/yil', grant:false },
  { id:13, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'4500$/yil', grant:true },
  { id:14, req:['Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Iqtisodiyot va Biznes','Menejment','Huquqshunoslik'], fee:'3500$/yil', grant:false },
  { id:15, req:['Attestat'], deg:['Bachelor','Master'], dir:['Huquqshunoslik','Iqtisodiyot va Biznes'], fee:'4000$/yil', grant:false },
  { id:16, req:['Attestat','Biologiya imtihoni'], deg:['Bachelor','Master'], dir:['Tibbiyot','Farmatsevtika'], fee:'5000$/yil', grant:false },
  { id:17, req:['Attestat','Biologiya imtihoni'], deg:['Bachelor','Master'], dir:['Tibbiyot'], fee:'4000$/yil', grant:false },
  { id:18, req:['Attestat','Biologiya imtihoni'], deg:['Bachelor','Master','PhD'], dir:['Tibbiyot','Farmatsevtika'], fee:'4200$/yil', grant:false },
  { id:19, req:['IELTS 6.0','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'6000$/yil', grant:true },
  { id:20, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Muhandislik','IT va Dasturlash'], fee:'2500$/yil', grant:true },
  { id:21, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Muhandislik','Energetika'], fee:'2800$/yil', grant:true },
  { id:22, req:['HSK 2','Attestat'], deg:['Bachelor'], dir:['Iqtisodiyot va Biznes','Turizm va Mehmonxona'], fee:'2000$/yil', grant:false },
  { id:23, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['Muhandislik','IT va Dasturlash','Tibbiyot'], fee:'2600$/yil', grant:true },
  { id:24, req:['HSK 3','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Iqtisodiyot va Biznes','Tilshunoslik','Muhandislik'], fee:'2400$/yil', grant:true },
  { id:25, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['Muhandislik','IT va Dasturlash','Iqtisodiyot va Biznes'], fee:'2500$/yil', grant:true },
  { id:26, req:['HSK 2','Attestat'], deg:['Bachelor'], dir:['Pedagogika','Tilshunoslik','Iqtisodiyot va Biznes'], fee:'2000$/yil', grant:true },
  { id:27, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['Energetika','Muhandislik','IT va Dasturlash'], fee:'2200$/yil', grant:true },
  { id:28, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['Muhandislik','Arxitektura','IT va Dasturlash'], fee:'2300$/yil', grant:true },
  { id:29, req:['HSK 2','Attestat'], deg:['Bachelor'], dir:['Turizm va Mehmonxona','Menejment'], fee:'2000$/yil', grant:false },
  { id:30, req:['HSK 2','Attestat'], deg:['Bachelor'], dir:['Muhandislik','Qurilish'], fee:'1800$/yil', grant:false },
  { id:31, req:['HSK 3','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Muhandislik','Iqtisodiyot va Biznes','Pedagogika'], fee:'2400$/yil', grant:true },
  { id:32, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Muhandislik','Energetika'], fee:'2600$/yil', grant:true },
  { id:33, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['Muhandislik','IT va Dasturlash','Iqtisodiyot va Biznes'], fee:'2800$/yil', grant:true },
  { id:34, req:['HSK 3','IELTS 5.0','Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Muhandislik','Iqtisodiyot va Biznes'], fee:'3000$/yil', grant:true },
  { id:35, req:['HSK 3','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Energetika','Muhandislik','IT va Dasturlash'], fee:'2800$/yil', grant:true },
  { id:36, req:['HSK 4','IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'3200$/yil', grant:true },
  { id:37, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['Pedagogika','Tilshunoslik','Muhandislik'], fee:'2200$/yil', grant:true },
  { id:38, req:['HSK 3','Attestat'], deg:['Bachelor','Master'], dir:['Muhandislik','IT va Dasturlash','Iqtisodiyot va Biznes'], fee:'2700$/yil', grant:true },
  { id:39, req:['HSK 4','IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'3500$/yil', grant:true },
  { id:40, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Menejment','IT va Dasturlash'], fee:'3500$/yil', grant:false },
  { id:41, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Iqtisodiyot va Biznes','IT va Dasturlash','Muhandislik'], fee:'3000$/yil', grant:true },
  { id:42, req:['Attestat'], deg:['Bachelor','Master','PhD'], dir:['Muhandislik','IT va Dasturlash','Iqtisodiyot va Biznes'], fee:'2500$/yil', grant:true },
  { id:43, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Muhandislik','IT va Dasturlash','Iqtisodiyot va Biznes','Menejment'], fee:'2800$/yil', grant:true },
  { id:44, req:['Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Pedagogika','Huquqshunoslik'], fee:'2000$/yil', grant:false },
  { id:45, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Tibbiyot','Farmatsevtika','Muhandislik'], fee:'4000$/yil', grant:true },
  { id:46, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'3500$/yil', grant:true },
  { id:47, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'4000$/yil', grant:true },
  { id:48, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Muhandislik','Iqtisodiyot va Biznes'], fee:'3500$/yil', grant:false },
  { id:49, req:['Attestat'], deg:['Bachelor'], dir:['Iqtisodiyot va Biznes','Menejment','Huquqshunoslik'], fee:'2500$/yil', grant:false },
  { id:50, req:['Attestat'], deg:['Bachelor'], dir:['Iqtisodiyot va Biznes','Menejment'], fee:'1500$/yil', grant:false },
  { id:51, req:['Attestat'], deg:['Bachelor'], dir:['Iqtisodiyot va Biznes','Pedagogika'], fee:'1800$/yil', grant:false },
  { id:52, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Iqtisodiyot va Biznes','Tilshunoslik'], fee:'2800$/yil', grant:false },
  { id:53, req:['Attestat'], deg:['Bachelor'], dir:['Muhandislik','IT va Dasturlash'], fee:'2000$/yil', grant:false },
  { id:54, req:['Attestat','Biologiya imtihoni'], deg:['Bachelor'], dir:['Tibbiyot','Farmatsevtika'], fee:'3000$/yil', grant:false },
  { id:55, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Iqtisodiyot va Biznes','Pedagogika'], fee:'2500$/yil', grant:false },
  { id:56, req:['Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Iqtisodiyot va Biznes','Tilshunoslik'], fee:'2200$/yil', grant:false },
  { id:57, req:['Attestat'], deg:['Bachelor'], dir:['Huquqshunoslik','Iqtisodiyot va Biznes','Tilshunoslik'], fee:'2000$/yil', grant:false },
  { id:58, req:['IELTS 5.5','Attestat'], deg:['Foundation','Bachelor','Master'], dir:['IT va Dasturlash','Iqtisodiyot va Biznes','Muhandislik','Menejment'], fee:'5000$/yil', grant:false },
  { id:59, req:['IELTS 5.0','Attestat'], deg:['Foundation','Bachelor','Master'], dir:['Iqtisodiyot va Biznes','IT va Dasturlash'], fee:'4000$/yil', grant:false },
  { id:60, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Iqtisodiyot va Biznes','Menejment'], fee:'2500$/yil', grant:false },
  { id:61, req:['IELTS 6.5','SAT 1300','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'18000$/yil', grant:true },
  { id:62, req:['IELTS 6.0','Attestat'], deg:['Foundation','Bachelor','Master'], dir:['IT va Dasturlash','Iqtisodiyot va Biznes','Menejment'], fee:'8000$/yil', grant:false },
  { id:63, req:['IELTS 6.0','Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Menejment','IT va Dasturlash'], fee:'7500$/yil', grant:false },
  { id:64, req:['TOPIK 4','IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'5500$/yil', grant:true },
  { id:65, req:['TOPIK 3','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'5000$/yil', grant:true },
  { id:66, req:['TOPIK 2','Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Muhandislik','IT va Dasturlash'], fee:'3500$/yil', grant:true },
  { id:67, req:['TOPIK 3','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Iqtisodiyot va Biznes','IT va Dasturlash','Tilshunoslik'], fee:'4000$/yil', grant:true },
  { id:68, req:['JLPT N3','Attestat'], deg:['Bachelor','Master'], dir:['IT va Dasturlash','Iqtisodiyot va Biznes'], fee:'4000$/yil', grant:false },
  { id:69, req:['IELTS 6.0','Attestat'], deg:['Master','PhD'], dir:['Muhandislik','IT va Dasturlash','Tibbiyot'], fee:'6000$/yil', grant:true },
  { id:70, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'3000$/yil', grant:true },
  { id:71, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Muhandislik','IT va Dasturlash','Iqtisodiyot va Biznes'], fee:'2800$/yil', grant:true },
  { id:72, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master'], dir:['Muhandislik','IT va Dasturlash','Iqtisodiyot va Biznes'], fee:'2600$/yil', grant:true },
  { id:73, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'2800$/yil', grant:true },
  { id:74, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'3200$/yil', grant:true },
  { id:75, req:['IELTS 5.0','Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Menejment','IT va Dasturlash'], fee:'2500$/yil', grant:false },
  { id:76, req:['IELTS 5.5','Attestat'], deg:['Foundation','Bachelor'], dir:['Muhandislik','Arxitektura','IT va Dasturlash'], fee:'5000$/yil', grant:true },
  { id:77, req:['IELTS 5.5','Attestat'], deg:['Foundation','Bachelor','Master'], dir:['Muhandislik','Tibbiyot','Arxitektura'], fee:'4500$/yil', grant:true },
  { id:78, req:['IELTS 5.5','Attestat'], deg:['Foundation','Bachelor','Master'], dir:['Tibbiyot','Muhandislik','Iqtisodiyot va Biznes'], fee:'4000$/yil', grant:true },
  { id:79, req:['IELTS 5.5','Attestat'], deg:['Foundation','Bachelor','Master','PhD'], dir:['*'], fee:'4500$/yil', grant:true },
  { id:80, req:['IELTS 6.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'500$/yil', grant:true },
  { id:81, req:['IELTS 6.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'500$/yil', grant:true },
  { id:82, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master'], dir:['Iqtisodiyot va Biznes','Menejment','Turizm va Mehmonxona','Huquqshunoslik'], fee:'3500$/yil', grant:false },
  { id:83, req:['IELTS 5.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['Muhandislik','IT va Dasturlash','Arxitektura','Energetika'], fee:'4000$/yil', grant:true },
  { id:84, req:['IELTS 5.5','Attestat'], deg:['Foundation','Bachelor'], dir:['*'], fee:'10000$/yil', grant:false },
  { id:85, req:['IELTS 6.0','Attestat'], deg:['Foundation','Bachelor','Master'], dir:['*'], fee:'12000$/yil', grant:true },
  { id:86, req:['IELTS 6.0','Attestat'], deg:['Foundation','Bachelor'], dir:['Iqtisodiyot va Biznes','IT va Dasturlash','Muhandislik'], fee:'10000$/yil', grant:false },
  { id:87, req:['IELTS 6.5','SAT 1100','Attestat'], deg:['Bachelor','Master'], dir:['*'], fee:'14000$/yil', grant:true },
  { id:88, req:['IELTS 6.0','Attestat'], deg:['Bachelor'], dir:['Iqtisodiyot va Biznes','IT va Dasturlash','Muhandislik'], fee:'10000$/yil', grant:false },
  { id:89, req:['IELTS 6.5','Attestat'], deg:['Bachelor','Master','PhD'], dir:['*'], fee:'12000$/yil', grant:true },
  { id:90, req:['IELTS 6.0','Attestat'], deg:['Bachelor'], dir:['IT va Dasturlash','Muhandislik','Menejment','Turizm va Mehmonxona'], fee:'9000$/yil', grant:false },
];

const upd = db.prepare('UPDATE universities SET requirements=?, degrees=?, directions=?, contract_fee=?, grant=? WHERE id=?');
const go = db.transaction(() => {
  data.forEach(u => {
    upd.run(
      JSON.stringify(u.req),
      JSON.stringify(u.deg),
      JSON.stringify(u.dir),
      u.fee,
      u.grant ? '1' : null,
      u.id
    );
  });
});
go();
console.log('Done! Updated', data.length, 'universities');
